# taken from https://github.com/yanntm/ITS-contribution
# and adapted

install: true

language: java

before_script:
 - echo $JAVA_OPTS
 - export JAVA_OPTS='-Xms1g -Xmx3g'
 - echo "MAVEN_OPTS='-Xmx3g'" > ~/.mavenrc

script : 
 - mvn -e -T 4 generate-sources install 

jdk: oraclejdk8

env:
  global:
    - MAVEN_OPTS="-Xmx3g"

cache:
  directories:
    - '$HOME/.m2/repository'
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: fr.lip6.veca.ide.updatesite/target/repository
  on:
    branch: master
