# taken from https://github.com/yanntm/ITS-contribution
# and adapted

install: true

language: java

# from https://muelder.blogspot.com/2015/08/building-eclipse-plugins-with-maven.html
# used to get a display for the tests
# else fails due to no display with "error: XDG_RUNTIME_DIR not set in the environment."

env:  
  global:  
    - DISPLAY=:99.0  
    - MAVEN_OPTS="-Xmx3g"
  before_install:  
    - sh -e /etc/init.d/xvfb start - sleep 10  

before_script:
 - echo $JAVA_OPTS
 - export JAVA_OPTS='-Xms1g -Xmx3g'
 - echo "MAVEN_OPTS='-Xmx3g'" > ~/.mavenrc

script : 
 - mvn -e install 

jdk: oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: fr.lip6.veca.ide.updatesite/target/repository
  on:
    branch: master
