# taken from https://github.com/yanntm/ITS-contribution
# and adapted with information from
# https://muelder.blogspot.com/2015/08/building-eclipse-plugins-with-maven.html
# https://docs.travis-ci.com/user/gui-and-headless-browsers/
# https://docs.travis-ci.com/user/deployment/pages/

# install: true

language: java
jdk:
- oraclejdk8
services:
- xvfb

env:  
  global:  
    - MAVEN_OPTS="-Xmx3g"

before_script:
 - echo $JAVA_OPTS
 - export JAVA_OPTS='-Xms1g -Xmx3g'
 - echo "MAVEN_OPTS='-Xmx3g'" > ~/.mavenrc
 - "export DISPLAY=:99.0"
# - "sh -e /etc/init.d/xvfb start"
 - sleep 10

script : 
 - mvn -e clean install 

cache:
  directories:
    - '$HOME/.m2/repository'
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  keep-history: true
  local-dir: fr.lip6.veca.ide.repository/target/repository
  target-branch: gh-pages
  on:
    branch: master
