/*
 * generated by Xtext 2.13.0
 */
package fr.lip6.veca.ide.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class VecaDslProposalProvider extends AbstractVecaDslProposalProvider {
}
