/*
 * generated by Xtext 2.13.0
 */
package fr.lip6.veca.ide


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class VecaDslStandaloneSetup extends VecaDslStandaloneSetupGenerated {

	def static void doSetup() {
		new VecaDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
