/*
 * generated by Xtext 2.13.0
 */
package fr.lip6.veca.ide


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class VecaDslRuntimeModule extends AbstractVecaDslRuntimeModule {
}
