/*
 * generated by Xtext 2.13.0
 */
package fr.lip6.veca.ide.ide

import com.google.inject.Guice
import fr.lip6.veca.ide.VecaDslRuntimeModule
import fr.lip6.veca.ide.VecaDslStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class VecaDslIdeSetup extends VecaDslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new VecaDslRuntimeModule, new VecaDslIdeModule))
	}
	
}
