/*
 * generated by Xtext 2.13.0
 */
package fr.lip6.veca.ide.tests

import com.google.inject.Inject
import fr.lip6.veca.ide.vecaDsl.Model
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(VecaDslInjectorProvider)
class VecaDslParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
		define
			basic component type A is
			signature
				messages m1, m2;
				provides op(m1): m2;
			behavior
				start in s0;
				stop in s2;
				s0: receive op then s1;
				s1: reply op then s2;
				s2:;
			end
		in
			a: A
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
}
